<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * This file contains the status of all Mouf global installation processes for packages you have installed.
 * If you are working with a source repository, this file should be commited.
 */
return array (
  0 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Constants\\DebugInstaller',
    'package' => 'mouf/utils.constants.debug',
  ),
  1 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironmentInstaller2',
    'package' => 'mouf/html.renderer.twig-extensions',
  ),
  2 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Constants\\SecretInstaller',
    'package' => 'mouf/utils.constants.secret',
  ),
  3 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Cache\\FileCacheInstaller',
    'package' => 'mouf/utils.cache.file-cache',
  ),
  4 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLoggerInstaller',
    'package' => 'mouf/utils.log.psr.errorlog_logger',
  ),
  5 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Cache\\ApcCacheInstaller',
    'package' => 'mouf/utils.cache.apc-cache',
  ),
  6 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.renderer',
  ),
  7 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManagerInstaller',
    'package' => 'mouf/html.utils.weblibrarymanager',
  ),
  8 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.menu',
  ),
  9 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.session.session-manager',
  ),
  10 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.messageservice',
  ),
  11 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplateInstaller',
    'package' => 'mouf/html.template.bootstrap',
  ),
  12 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Cache\\CacheInstaller',
    'package' => 'mouf/utils.common.doctrine-cache-wrapper',
  ),
  13 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Annotations\\AnnotationReaderInstaller',
    'package' => 'mouf/utils.common.doctrine-annotations-wrapper',
  ),
  14 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splash8install/',
    'package' => 'mouf/mvc.splash',
  ),
  15 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splash8install/writeHtAccess',
    'package' => 'mouf/mvc.splash',
  ),
);